{
 "title": "Pod Stats & Info",
 "description": "This is for insight on important Kubernetes app metrics.\r\nWhat recources is a Pod actually using and what are it's limits or requests and what part is each container consuming?\r\nAlso has graphs for networking, disks, restarts docker images etc",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_labels, namespace)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "label": "container",
    "query": "label_values(kube_pod_container_info{namespace=\"$namespace\",pod=\"$pod\"}, container)"
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Memory: $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"POD\",container!=\"\",pod!=\"\", pod=\"$pod\"})",
     "legendFormat": "MEM"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU: $pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"$namespace\",pod=\"$pod\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"POD\",container!=\"\",pod!=\"\", pod=\"$pod\"}[1m]))",
     "legendFormat": "CPU: $pod"
    }
   ]
  },
  {
   "title": "Network: $pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[5m]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{namespace=\"$namespace\",pod=\"$pod\"}[5m]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Info: $pod",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "kube_pod_container_info{namespace=\"$namespace\",pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Pod created",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 31 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_pod_created{namespace=\"$namespace\",pod=\"$pod\"} * 1000",
     "legendFormat": "$pod"
    }
   ]
  },
  {
   "title": "Network-Errors: $pod",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) / sum(rate(container_network_receive_errors_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) * 100",
     "legendFormat": "Receive-Errors%"
    },
    {
     "expr": "sum(rate(container_network_receive_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) / sum(rate(container_network_receive_packets_dropped_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) * 100",
     "legendFormat": "Receive-Dropped%"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) / sum(rate(container_network_transmit_errors_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) * 100",
     "legendFormat": "Transmit-Errors%"
    },
    {
     "expr": "sum(rate(container_network_transmit_packets_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) / sum(rate(container_network_receive_packets_dropped_total{namespace=\"$namespace\",pod=\"$pod\"}[5m])) * 100",
     "legendFormat": "Transmit-Dropped%"
    }
   ]
  },
  { "title": "Restarts & Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Ready: $container",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
   "repeat": "container",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_ready{namespace=\"$namespace\",pod=\"$pod\",container=\"$container\"}",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Restarts: $container",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 45 },
   "repeat": "container",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(kube_pod_container_status_restarts_total{namespace=\"$namespace\",pod=\"$pod\", container=\"$container\"}[1m])",
     "legendFormat": "{{ container }}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\", pod=\"$pod\"} > 0"
    }
   ]
  },
  {
   "title": "Waiting Reason",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "kube_pod_container_status_waiting_reason{namespace=\"$namespace\", pod=\"$pod\"} > 0"
    }
   ]
  },
  { "title": "Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } }
 ]
}